# Generated by Django 4.2.9 on 2024-01-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='The title of the book.', max_length=70)),
                ('publication_date', models.DateField(default=None, verbose_name='Date the book was published.')),
                ('isbn', models.CharField(default=None, max_length=20, verbose_name='ISBN number of the book.')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.publisher')),
            ],
        ),
    ]
